name: tagpr
on:
  push:
    branches: ["main"]
jobs:
  tagpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.TAGPR_GH_SECRET }}
      - uses: Songmu/tagpr@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TAGPR_GH_SECRET }}
